FROM python:3.8.13-slim

COPY ./app /app

WORKDIR /app

RUN pip install -r requirements.txt \
  && groupadd -r runner && useradd -g runner runner \
  && chown -R runner:runner /app

USER runner

EXPOSE 8080

CMD streamlit run app.py --server.port $PORT
